spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;
    username: user1
    password: user1
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml


logging:
  level:
    liquibase: INFO